// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YourChoice.Api.Database;

namespace YourChoice.Api.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20201112195208_default rg_date")]
    partial class defaultrg_date
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("YourChoice.Domain.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("YourChoice.Domain.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("YourChoice.Domain.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("CanBePublished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Post");
                });

            modelBuilder.Entity("YourChoice.Domain.PostPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("PostParts");

                    b.HasDiscriminator<string>("Discriminator").HasValue("PostPart");
                });

            modelBuilder.Entity("YourChoice.Domain.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("YourChoice.Domain.Subscription", b =>
                {
                    b.Property<int?>("ToWhomId")
                        .HasColumnType("int");

                    b.Property<int?>("WhoId")
                        .HasColumnType("int");

                    b.HasKey("ToWhomId", "WhoId");

                    b.HasIndex("WhoId");

                    b.ToTable("Subscription");
                });

            modelBuilder.Entity("YourChoice.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Login")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 11, 12, 21, 52, 7, 402, DateTimeKind.Local).AddTicks(607));

                    b.Property<string>("Surname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasFilter("[Login] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("YourChoice.Domain.PhotoPost", b =>
                {
                    b.HasBaseType("YourChoice.Domain.Post");

                    b.HasDiscriminator().HasValue("PhotoPost");
                });

            modelBuilder.Entity("YourChoice.Domain.VideoPost", b =>
                {
                    b.HasBaseType("YourChoice.Domain.Post");

                    b.HasDiscriminator().HasValue("VideoPost");
                });

            modelBuilder.Entity("YourChoice.Domain.PhotoPostPart", b =>
                {
                    b.HasBaseType("YourChoice.Domain.PostPart");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhotoPostId")
                        .HasColumnType("int");

                    b.HasIndex("PhotoPostId");

                    b.HasDiscriminator().HasValue("PhotoPostPart");
                });

            modelBuilder.Entity("YourChoice.Domain.VideoPostPart", b =>
                {
                    b.HasBaseType("YourChoice.Domain.PostPart");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VideoPostPart_Link");

                    b.Property<int?>("VideoPostId")
                        .HasColumnType("int");

                    b.HasIndex("VideoPostId");

                    b.HasDiscriminator().HasValue("VideoPostPart");
                });

            modelBuilder.Entity("YourChoice.Domain.Comment", b =>
                {
                    b.HasOne("YourChoice.Domain.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("YourChoice.Domain.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YourChoice.Domain.Message", b =>
                {
                    b.HasOne("YourChoice.Domain.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("YourChoice.Domain.Post", b =>
                {
                    b.HasOne("YourChoice.Domain.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("YourChoice.Domain.Rating", b =>
                {
                    b.HasOne("YourChoice.Domain.Post", "Post")
                        .WithMany("Rating")
                        .HasForeignKey("PostId");

                    b.HasOne("YourChoice.Domain.User", "User")
                        .WithMany("Rating")
                        .HasForeignKey("UserId");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YourChoice.Domain.Subscription", b =>
                {
                    b.HasOne("YourChoice.Domain.User", "ToWhom")
                        .WithMany("Subscribers")
                        .HasForeignKey("ToWhomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YourChoice.Domain.User", "Who")
                        .WithMany("Subscriptions")
                        .HasForeignKey("WhoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ToWhom");

                    b.Navigation("Who");
                });

            modelBuilder.Entity("YourChoice.Domain.PhotoPostPart", b =>
                {
                    b.HasOne("YourChoice.Domain.PhotoPost", "Post")
                        .WithMany("PostParts")
                        .HasForeignKey("PhotoPostId");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("YourChoice.Domain.VideoPostPart", b =>
                {
                    b.HasOne("YourChoice.Domain.VideoPost", "Post")
                        .WithMany("PostParts")
                        .HasForeignKey("VideoPostId");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("YourChoice.Domain.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("YourChoice.Domain.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Messages");

                    b.Navigation("Posts");

                    b.Navigation("Rating");

                    b.Navigation("Subscribers");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("YourChoice.Domain.PhotoPost", b =>
                {
                    b.Navigation("PostParts");
                });

            modelBuilder.Entity("YourChoice.Domain.VideoPost", b =>
                {
                    b.Navigation("PostParts");
                });
#pragma warning restore 612, 618
        }
    }
}
